MSDiary/Models/Rendimento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MSDiary.Models
{
    public class Rendimento
    {

        public int RendimentoId { get; set; }

        public int TipoRendimentoId { get; set; }

        [Display(Name = "Descrição do Rendimento")]
        [Required]
        public string RendimentoDescricao { get; set; }

        [Display(Name = "Valor")]
        [Required]
        public decimal RendimentoValor { get; set; }

        [Display(Name = "Data")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime Data { get; set; }

        [Display(Name = "Comentário")]
        public string Comentario { get; set; }

        public TipoRendimento TipoRendimento { get; set; }

        public virtual ApplicationUser User { get; set; }

        public string ApplicationUserId { get; set; }
    }
}

MSDiary/Controllers/RendimentosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MSDiary.Models;
using Microsoft.AspNet.Identity;

namespace MSDiary.Controllers
{
    public class RendimentosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Rendimentos
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var rendimentos = db.Rendimentos.Include(r => r.TipoRendimento).Where(d => d.ApplicationUserId == userId);
            return View(rendimentos.ToList());
        }

        [HttpPost]
        public ActionResult Index(string pesquisa)
        {
            var userId = User.Identity.GetUserId();
            var resultado = from r in db.Rendimentos.Include(r => r.TipoRendimento).Where(r => r.ApplicationUserId == userId)
            select r;

            if (!String.IsNullOrEmpty(pesquisa))
            {
                DateTime d = Convert.ToDateTime(pesquisa);
                resultado = resultado.Where(r => r.Data == d);
            }

            return View(resultado);
        }

        // GET: Rendimentos/Details/5
        public ActionResult Details(int? id)
        {
            var modelo = db.Rendimentos.Include("TipoRendimento").Where(p => p.RendimentoId == id).FirstOrDefault();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (modelo == null)
            {
                return HttpNotFound();
            }
            ViewModelDetalhesRendimento model = new ViewModelDetalhesRendimento()
            {
                TipoRendimento = modelo.TipoRendimento.TipoRendimentoNome,
                Descricao = modelo.RendimentoDescricao,
                Data = modelo.Data,
                Valor = modelo.RendimentoValor,
                comentario = modelo.Comentario,

            };

            return View(model);
        }

        // GET: Rendimentos/Create
        public ActionResult Create()
        {
            var userId = User.Identity.GetUserId();
            ViewBag.TipoRendimentoId = new SelectList(db.TipoRendimentos.Where(m => m.ApplicationUserId == userId), "TipoRendimentoId", "TipoRendimentoNome");
            return View();
        }

        // POST: Rendimentos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RendimentoId,TipoRendimentoId,RendimentoDescricao,RendimentoValor,Data,Comentario")] Rendimento rendimento)
        {
            var userId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                rendimento.ApplicationUserId = User.Identity.GetUserId();

                var saldo = db.Saldo.Where(d => d.ApplicationUserId == userId).FirstOrDefault();

                if (saldo == null)
                {
                    var s = new Saldo();
                    s.Rendimentos.Add(rendimento);
                    s.ApplicationUserId = userId;
                    db.Saldo.Add(s);
                }
                else
                {
                    saldo.Rendimentos.Add(rendimento);
                }

        

                
                db.Rendimentos.Add(rendimento);
                db.SaveChanges();

                SaldoUtilizador saldoUtilizador = new SaldoUtilizador()
                {
                    ApplicationUserId = userId,
                    data = rendimento.Data,
                    rendimentoId = rendimento.RendimentoId,
                    valor = rendimento.RendimentoValor,
                    TipoRendimentoId = rendimento.TipoRendimentoId,
                };

                db.SaldoUtilizadores.Add(saldoUtilizador);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.TipoRendimentoId = new SelectList(db.TipoRendimentos.Where(m => m.ApplicationUserId == userId), "TipoRendimentoId", "TipoRendimentoNome", rendimento.TipoRendimentoId);
            return View(rendimento);
        }

        // GET: Rendimentos/Edit/5
        public ActionResult Edit(int? id)
        {

            var userId = User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rendimento rendimento = db.Rendimentos.Find(id);
            if (rendimento == null)
            {
                return HttpNotFound();
            }
            ViewBag.TipoRendimentoId = new SelectList(db.TipoRendimentos.Where(m => m.ApplicationUserId == userId), "TipoRendimentoId", "TipoRendimentoNome", rendimento.TipoRendimentoId);
            return View(rendimento);
        }

        // POST: Rendimentos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RendimentoId,TipoRendimentoId,RendimentoDescricao,RendimentoValor,Data,Comentario")] Rendimento rendimento)
        {
            var userId = User.Identity.GetUserId();
            rendimento.ApplicationUserId = userId;
            var rendimentoUtilizador = db.SaldoUtilizadores.Where(x => x.rendimentoId == rendimento.RendimentoId).Where(x => x.ApplicationUserId == userId).First();
            rendimentoUtilizador.valor = rendimento.RendimentoValor;
            rendimentoUtilizador.data = rendimento.Data;
            if (ModelState.IsValid)
            {
                db.Entry(rendimentoUtilizador).State = EntityState.Modified;
                db.Entry(rendimento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TipoRendimentoId = new SelectList(db.TipoRendimentos.Where(m => m.ApplicationUserId == userId), "TipoRendimentoId", "TipoRendimentoNome", rendimento.TipoRendimentoId);
            return View(rendimento);
        }

        // GET: Rendimentos/Delete/5
        public ActionResult Delete(int? id)
        {
            var modelo = db.Rendimentos.Include("TipoRendimento").Where(p => p.RendimentoId == id).FirstOrDefault();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (modelo == null)
            {
                return HttpNotFound();
            }

            ViewModelDetalhesRendimento model = new ViewModelDetalhesRendimento()
            {
                TipoRendimento = modelo.TipoRendimento.TipoRendimentoNome,
                Descricao = modelo.RendimentoDescricao,
                Data = modelo.Data,
                Valor = modelo.RendimentoValor,
                comentario = modelo.Comentario,

            };

            return View(model);
        }

        // POST: Rendimentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var userId = User.Identity.GetUserId();
            var rendimentoUtilizador = db.SaldoUtilizadores.Where(x => x.rendimentoId == id).Where(x => x.ApplicationUserId == userId).First();
            Rendimento rendimento = db.Rendimentos.Find(id);
            db.Rendimentos.Remove(rendimento);
            db.SaldoUtilizadores.Remove(rendimentoUtilizador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MSDiary/Views/Rendimentos/Create.cshtml
@model MSDiary.Models.Rendimento

@{
    ViewBag.Title = "Create";
}

<hr />
<h2>Criar Rendimentos</h2>
<hr />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TipoRendimentoId, "TipoRendimentoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoRendimentoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoRendimentoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RendimentoDescricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RendimentoDescricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RendimentoDescricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RendimentoValor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RendimentoValor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RendimentoValor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comentario,8,40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MSDiary/Views/Rendimentos/Delete.cshtml
@model MSDiary.Models.ViewModelDetalhesRendimento

@{
    Layout = null;
    ViewBag.Title = "Delete";
}

<br />
<br />
<div class="modal-dialog">
    <div class="modal-content">
        @using (Html.BeginForm())
        {
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Tem a certeza que pretende eliminar a despesa?</h4>
            </div>
            @Html.AntiForgeryToken()
            <div class="modal-body">
                <p>@Html.LabelFor(model => model.TipoRendimento) : @Html.DisplayFor(model => model.TipoRendimento)</p>
                <p>@Html.LabelFor(model => model.Descricao) : @Html.DisplayFor(model => model.Descricao)</p>
                <p>@Html.LabelFor(model => model.Valor) : @Html.DisplayFor(model => model.Valor)€</p>
                <p>@Html.LabelFor(model => model.Data) : @Html.DisplayFor(model => model.Data)</p>
                @if (Model.comentario != null)
                {
                    <p>@Html.LabelFor(model => model.comentario) : @Html.DisplayFor(model => model.comentario)</p>
                }
            </div>
            <div class="modal-footer">
                <input type="submit" value="Eliminar" class="btn btn-primary" />
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        }
    </div>
</div>

MSDiary/Views/Rendimentos/Details.cshtml
@model MSDiary.Models.ViewModelDetalhesRendimento

@{
    Layout = null;
    ViewBag.Title = "Details";
}

<br />
<br />
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Detalhes do produto</h4>
        </div>
        <div class="modal-body">
            <p>@Html.LabelFor(model => model.TipoRendimento) : @Html.DisplayFor(model => model.TipoRendimento)</p>
            <p>@Html.LabelFor(model => model.Descricao) : @Html.DisplayFor(model => model.Descricao)</p>
            <p>@Html.LabelFor(model => model.Valor) : @Html.DisplayFor(model => model.Valor)€</p>
            <p>@Html.LabelFor(model => model.Data) : @Html.DisplayFor(model => model.Data)</p>
            @if (Model.comentario != null)
            {
                <p>@Html.LabelFor(model => model.comentario) : @Html.DisplayFor(model => model.comentario)</p>
            }
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

MSDiary/Views/Rendimentos/Edit.cshtml
@model MSDiary.Models.Rendimento

@{
    Layout = null;
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div class="modal-dialog">
    <div class="modal-content">
        @using (Html.BeginForm())
        {
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Editar Despesa</h4>
            </div>

            @Html.AntiForgeryToken()
            <div class="modal-body">
                <div class="form-horizontal">
                    <h4>Rendimento</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.RendimentoId)

                    <div class="form-group">
                        @Html.LabelFor(model => model.TipoRendimentoId, "TipoRendimentoId", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("TipoRendimentoId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TipoRendimentoId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.RendimentoDescricao, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.RendimentoDescricao, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.RendimentoDescricao, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.RendimentoValor, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.RendimentoValor, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.RendimentoValor, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                           @Html.TextAreaFor(model => model.Comentario,8,40, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" value="Editar" class="btn btn-primary" />
                <input type="button" value="Cancelar" class="btn btn-default" data-dismiss="modal" />
            </div>
        }
    </div>
</div>


MSDiary/Views/Rendimentos/Index.cshtml
@model IEnumerable<MSDiary.Models.Rendimento>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="row">
        <hr />
        <h2 class="text-center">Lista de Rendimentos</h2>
        <hr />
    </div>
    <div class="row paddingTop">
        <div class="col-md-2">
            <a href="@Url.Action("Create", "Rendimentos")" class="btn btn-success" data-toggle="tooltip" title="Adiciona uma despesa" style="float: left;">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </a>
        </div>
        @using (Html.BeginForm())
        {
            <div class="form-horizontal">
                <label class="control-label col-md-1 text-right">Data</label>
                <div class="col-md-2">
                    <input type="date" class="form-control" name="pesquisa" />
                </div>
                <div class="col-md-1">
                    <button type="submit" class="btn btn-default" data-toggle="tooltip" title="Pesquisar por data"><span class="glyphicon glyphicon-search"></span></button>
                </div>

            </div>
        }
    </div>
</div>
<div class="row paddingTop">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TipoRendimento.TipoRendimentoNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RendimentoDescricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RendimentoValor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoRendimento.TipoRendimentoNome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RendimentoDescricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RendimentoValor)€
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data)
                </td>
                <td>
                    <button class="btn btn-default detailsRendimentos" data-id="@item.RendimentoId" data-toggle="tooltip" title="Detalhes do Rendimento"><i class="glyphicon glyphicon-file"></i></button>
                    <button class="btn btn-danger deleteRendimentos" data-id="@item.RendimentoId" data-toggle="tooltip" title="Eliminar Rendimento"><i class="glyphicon glyphicon-trash"></i></button>
                    <button class="btn btn-primary editRendimentos" data-id="@item.RendimentoId" data-toggle="tooltip" title="Editar Rendimento"><i class="glyphicon glyphicon-edit"></i></button>
                </td>
            </tr>
        }

    </table>
    <div class="modal" id="modal">

    </div>
</div>
@section scripts{
    <script src="~/Scripts/CRUD/CRUD.js"></script>
}