MSDiary/Models/Despesa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MSDiary.Models
{
    public class Despesa
    {
        public int TipoDespesaId { get; set; }

        public int DespesaId { get; set; }

        [Display(Name = "Descrição da Despesa")]
        [Required]
        public string DespesaDescricao { get; set; }

        [Display(Name = "Valor")]
        [Required]
        public decimal DespesaValor { get; set; }

        public int TipoPagamentoId { get; set; }

        [Display(Name = "Data")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}",ApplyFormatInEditMode = true)]
        [Required]
        public DateTime Data { get; set; }

        public TipoDespesa TipoDespesa { get; set; }

        public TipoPagamento TipoPagamento { get; set; }

        [Display(Name = "Comentário")]
        public string Comentario { get; set; }

        [ForeignKey("ApplicationUserId")]
        public virtual ApplicationUser User { get; set; }

        public string ApplicationUserId { get; set; }

    }
}

MSDiary/Controllers/DespesasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MSDiary.Models;
using Microsoft.AspNet.Identity;
using System.Web.Security;
using System.Threading.Tasks;
using MSDiary.Helper;
using System.Net.Http;
using Newtonsoft.Json;

namespace MSDiary.Controllers
{
    public class DespesasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Despesas
        /*public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var despesas = db.Despesas.Include(d => d.TipoDespesa).Include(d => d.TipoPagamento).Include(d => d.TipoDespesa.subTipo).Where(d => d.ApplicationUserId == userId);
            System.Diagnostics.Debug.WriteLine(userId);
            ViewBag.TipoDespesa = new SelectList(db.TipoDespesas, "TipoDespesaId", "TipoDespesaNome");
            return View(despesas.ToList());
        }
        */
        public async Task<ActionResult> Index()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Despesas");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var despesa =
                JsonConvert.DeserializeObject<IEnumerable<Despesa>>(content);
                return View(despesa);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }
        }
        [HttpPost]
        public ActionResult Index(string pesquisa,string tipoDespesa)
        {            ViewBag.TipoDespesa = new SelectList(db.TipoDespesas, "TipoDespesaId", "TipoDespesaNome",tipoDespesa);
            var userId = User.Identity.GetUserId();
            var resultado = from r in db.Despesas.Include(r => r.TipoDespesa).Include(r => r.TipoPagamento).Where(r => r.ApplicationUserId == userId)
                            select r;

            if (!String.IsNullOrEmpty(pesquisa))
            {
                DateTime d = Convert.ToDateTime(pesquisa);
                resultado = resultado.Where(r => r.Data == d);
            }

            if(tipoDespesa != "")
            {
                int tipo = Convert.ToInt32(tipoDespesa);
               resultado = resultado.Where(r => r.TipoDespesaId == tipo);
            }

            return View(resultado);
        }

        // GET: Despesas/Details/5
        /*public ActionResult Details(int? id)
        {
            var modelo = db.Despesas.Include("TipoDespesa").Include("TipoPagamento").Where(p => p.DespesaId == id).FirstOrDefault();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            if (modelo == null)
            {
                return HttpNotFound();
            }
            ViewModelDetalhesDespesa model = new ViewModelDetalhesDespesa()
            {
                TipoDespesa = modelo.TipoDespesa.TipoDespesaNome,
                subtTipoDespesa = modelo.TipoDespesa.subTipo,
                TipoPagamento = modelo.TipoPagamento.TipoPagamentoNome,
                Descricao = modelo.DespesaDescricao,
                Data = modelo.Data,
                Valor = modelo.DespesaValor,
                comentario = modelo.Comentario,


            };
            return View(model);
        }*/

        // GET: Produtos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Despesas/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var despesa = JsonConvert.DeserializeObject<Despesa>(content);
                if (despesa == null) return HttpNotFound();
                return View(despesa);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }
        }

        // GET: Despesas/Create
        public ActionResult Create()
        {
            var userId = User.Identity.GetUserId();
            ViewBag.TipoDespesaId = new SelectList(db.TipoDespesas.Where(m => m.ApplicationUserId == userId), "TipoDespesaId", "TipoDespesaNome");
            ViewBag.TipoPagamentoId = new SelectList(db.TipoPagamentos.Where(m => m.ApplicationUserId == userId), "TipoPagamentoId", "TipoPagamentoNome");
            return View();
        }

        // POST: Despesas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DespesaId,TipoDespesaId,subTipo,DespesaDescricao,DespesaValor,TipoPagamentoId,Data,Comentario,ApplicationUserId")] Despesa despesa)
        {
            var userId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {

                var saldo = db.Saldo.Where(d => d.ApplicationUserId == userId).FirstOrDefault();
                despesa.ApplicationUserId = userId;

                if (saldo == null)
                {
                    var s = new Saldo();
                    s.Despesas.Add(despesa);
                    s.ApplicationUserId = userId;
                    db.Saldo.Add(s);
   
                }
                else
                {
                    saldo.Despesas.Add(despesa);
                }

                db.Despesas.Add(despesa);
                db.SaveChanges();

                SaldoUtilizador saldoUtilizador = new SaldoUtilizador()
                {
                    ApplicationUserId = userId,
                    data = despesa.Data,
                    despesaId = despesa.DespesaId,
                    valor = -despesa.DespesaValor,
                    TipoDespesaId = despesa.TipoDespesaId,
                };

                db.SaldoUtilizadores.Add(saldoUtilizador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TipoDespesaId = new SelectList(db.TipoDespesas.Where(m => m.ApplicationUserId == userId), "TipoDespesaId", "TipoDespesaNome", despesa.TipoDespesaId);
            ViewBag.TipoPagamentoId = new SelectList(db.TipoPagamentos.Where(m => m.ApplicationUserId == userId), "TipoPagamentoId", "TipoPagamentoNome", despesa.TipoPagamentoId);
            return View(despesa);
        }
        */

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "DespesaId,TipoDespesaId,subTipo,DespesaDescricao,DespesaValor,TipoPagamentoId,Data,Comentario,ApplicationUserId")] Despesa despesa)
        {
            try
            {
                var client = WebApiHttpClient.GetClient();
                string produtoJSON = JsonConvert.SerializeObject(despesa);
                HttpContent content = new StringContent(produtoJSON,
                System.Text.Encoding.Unicode, "application/json");
                var response = await client.PostAsync("api/Despesas", content);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }
            }
            catch
            {
                return Content("Ocorreu um erro.");
            }
        }

        // GET: Despesas/Edit/5
        /*public ActionResult Edit(int? id)
        {
            var userId = User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Despesa despesa = db.Despesas.Find(id);
            if (despesa == null)
            {
                return HttpNotFound();
            }
            ViewBag.TipoDespesaId = new SelectList(db.TipoDespesas.Where(m => m.ApplicationUserId == userId), "TipoDespesaId", "TipoDespesaNome", despesa.TipoDespesaId);
            ViewBag.TipoPagamentoId = new SelectList(db.TipoPagamentos.Where(m => m.ApplicationUserId == userId), "TipoPagamentoId", "TipoPagamentoNome", despesa.TipoPagamentoId);
            return View(despesa);
        }*/

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Produtos/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var despesa = JsonConvert.DeserializeObject<Despesa>(content);
                if (despesa == null) return HttpNotFound();
                return View(despesa);
            }
            return Content("Ocorreu um erro: " + response.StatusCode);
        }

        // POST: Despesas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

MSDiary/Views/Despesas/Create.cshtml
@model MSDiary.Models.Despesa

@{
    ViewBag.Title = "Criar Despesa";
}


<hr />
<h2>Criar Despesa</h2>
<hr />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TipoDespesaId, "Tipo de Despesa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoDespesaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoDespesaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DespesaDescricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DespesaDescricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DespesaDescricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DespesaValor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DespesaValor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DespesaValor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoPagamentoId, "Tipo de Pagamento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoPagamentoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoPagamentoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comentario,8,40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MSDiary/Views/Despesas/Delete.cshtml
@model MSDiary.Models.ViewModelDetalhesDespesa

@{
    Layout = null;
    ViewBag.Title = "Delete";
}
<br />
<br />
<div class="modal-dialog">
    <div class="modal-content">
@using (Html.BeginForm())
{
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Tem a certeza que pretende eliminar a despesa?</h4>
        </div>
        @Html.AntiForgeryToken()
        <div class="modal-body">
            <p>@Html.LabelFor(model => model.TipoDespesa) : @Html.DisplayFor(model => model.TipoDespesa)</p>
            <p>@Html.LabelFor(model => model.TipoPagamento) : @Html.DisplayFor(model => model.TipoPagamento)</p>
            <p>@Html.LabelFor(model => model.Descricao) : @Html.DisplayFor(model => model.Descricao)</p>
            <p>@Html.LabelFor(model => model.Valor) : @Html.DisplayFor(model => model.Valor)€</p>
            <p>@Html.LabelFor(model => model.Data) : @Html.DisplayFor(model => model.Data)</p>
            @if (Model.comentario != null)
            {
                <p>@Html.LabelFor(model => model.comentario) : @Html.DisplayFor(model => model.comentario)</p>
            }
        </div>
        <div class="modal-footer">
             <input type="submit" value="Eliminar" class="btn btn-primary" />
             <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
            }
    </div>
    </div>

MSDiary/Views/Despesas/Details.cshtml
@model MSDiary.Models.ViewModelDetalhesDespesa

@{
    {
        Layout = null;
        ViewBag.Title = "Details";
    }
}


<br />
<br />
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Detalhes do produto</h4>
        </div>
        <div class="modal-body">
            <p>@Html.LabelFor(model => model.TipoDespesa) : @Html.DisplayFor(model => model.TipoDespesa)</p>  
            <p>@Html.LabelFor(model => model.TipoPagamento) : @Html.DisplayFor(model => model.TipoPagamento)</p>  
            <p>@Html.LabelFor(model => model.Descricao) : @Html.DisplayFor(model => model.Descricao)</p>  
            <p>@Html.LabelFor(model => model.Valor) : @Html.DisplayFor(model => model.Valor)€</p>  
            <p>@Html.LabelFor(model => model.Data) : @Html.DisplayFor(model => model.Data)</p>  
            @if(Model.comentario != null)
            {
             <p>@Html.LabelFor(model => model.comentario) : @Html.DisplayFor(model => model.comentario)</p> 
            }         
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

MSDiary/Views/Despesas/Edit.cshtml
@model MSDiary.Models.Despesa

@{
    Layout = null;
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div class="modal.content">
    <div class="modal-content">
@using (Html.BeginForm())
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Editar Despesa</h4>
    </div>

    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.DespesaId)

            <div class="form-group">
                @Html.LabelFor(model => model.TipoDespesaId, "TipoDespesaId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TipoDespesaId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TipoDespesaId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DespesaDescricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DespesaDescricao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DespesaDescricao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DespesaValor, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DespesaValor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DespesaValor, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TipoPagamentoId, "TipoPagamentoId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TipoPagamentoId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TipoPagamentoId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Comentario,8,40, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="submit" value="Editar" class="btn btn-primary" />
        <input type="button" value="Cancelar" class="btn btn-default" data-dismiss="modal" />
    </div>
        }
    </div>
   </div>

MSDiary/Views/Despesas/Index.cshtml
@model IEnumerable<MSDiary.Models.Despesa>

@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="row">
        <hr />
        <h2 class="text-center">Lista de despesas</h2>
        <hr />
    </div>
        <div class="row paddingTop">
            <div class="form-inline">    
                @using (Html.BeginForm())
                {
                    <div class="form-group">
                        <a href="@Url.Action("Create", "Despesas")" class="btn btn-danger" data-toggle="tooltip" title="Adiciona uma despesa" style="float: left;">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </a>
                    </div>
                    <div class="form-group col-md-offset-1">
                        <label class="control-label">Tipo de despesa</label>
                        @Html.DropDownList("TipoDespesa", (IEnumerable<SelectListItem>)ViewBag.TipoDespesa, "Todos", htmlAttributes: new { @class = "form-control" })
                    </div>
                        <div class="form-group"style="padding-left:20px">
                            <label class="control-label">Data</label>
                            <input type="date" class="form-control" name="pesquisa" />
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default" data-toggle="tooltip" title="Pesquisar por data"><span class="glyphicon glyphicon-search"></span></button>
                        </div>

                }
            </div>

        </div>
    </div>
        <div class="row paddingTop">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TipoDespesa.TipoDespesaNome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipoDespesa.subTipo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DespesaDescricao)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DespesaValor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Data)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoDespesa.TipoDespesaNome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoDespesa.subTipo.TipoDespesaNome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DespesaDescricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DespesaValor)€
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Data)
                    </td>
                    <td>
                        <button class="btn btn-default details" data-id="@item.DespesaId" data-toggle="tooltip" title="Detalhes da despesa"><i class="glyphicon glyphicon-file"></i></button>
                        <button class="btn btn-danger delete" data-id="@item.DespesaId" data-toggle="tooltip" title="Eliminar despesa"><i class="glyphicon glyphicon-trash"></i></button>
                        <button class="btn btn-primary edit" data-id="@item.DespesaId" data-toggle="tooltip" title="Editar despesa"><i class="glyphicon glyphicon-edit"></i></button>
                    </td>
                </tr>
            }

        </table>
        <div class="modal" id="modal">

        </div>
    </div>
@section scripts{
    <script src="~/Scripts/CRUD/CRUD.js"></script>
}